import { PatternName, VerificationResult, VerifyOptions } from '../config/types';

import { Logger } from '../utils/logger';
import { formatDateUTC, getUTCDayOfWeek } from '../utils/timezone';
import { GitExec } from './gitExec';

export class Verifier {
  /**
   * Scans git repository history and verifies pattern compliance.
   */
  public static verify(options: VerifyOptions = {}): VerificationResult {
    const patternName: PatternName = options.pattern ?? 'all-but-sat';
    Logger.info(`Starting Git History Verification for pattern rule '${patternName}'...`);

    const commits = GitExec.getCommitLog(options.maxCommits ?? 5000, options.cwd);
    let totalScanned = commits.length;
    let matchingCanvasCommits = 0;
    let saturdayCommitsFound = 0;
    const violatingCommits: Array<{ hash: string; dateStr: string; message: string }> = [];

    for (const commit of commits) {
      // Check if commit is generated by commit-canvas-filter or part of history
      const isCanvasCommit = commit.message.includes('[commit-canvas-filter:');
      if (isCanvasCommit) {
        matchingCanvasCommits++;
      }

      // Evaluate commit timestamp UTC day of week
      const dateObj = new Date(commit.isoDate);
      if (isNaN(dateObj.getTime())) {
        continue;
      }

      const dayOfWeek = getUTCDayOfWeek(dateObj);
      const dateStr = formatDateUTC(dateObj);

      // Rule 'all-but-sat': Saturday (6) is strictly prohibited
      if (dayOfWeek === 6) {
        if (isCanvasCommit || options.pattern === 'all-but-sat') {
          saturdayCommitsFound++;
          violatingCommits.push({
            hash: commit.hash.substring(0, 8),
            dateStr,
            message: commit.message,
          });
        }
      }
    }

    const success = saturdayCommitsFound === 0;
    const summary = success
      ? `VERIFICATION PASSED: Scanned ${totalScanned} commits (${matchingCanvasCommits} commit-canvas commits). Zero Saturday commits found!`
      : `VERIFICATION FAILED: Scanned ${totalScanned} commits. Found ${saturdayCommitsFound} prohibited Saturday commit(s)!`;

    if (success) {
      Logger.success(summary);
    } else {
      Logger.error(summary);
      Logger.error('Violating Saturday Commits:');
      for (const v of violatingCommits) {
        Logger.error(`  - Hash: ${v.hash} | Date: ${v.dateStr} | Msg: ${v.message}`);
      }
    }

    return {
      success,
      patternName,
      totalCommitsScanned: totalScanned,
      matchingCanvasCommits,
      saturdayCommitsFound,
      violatingCommits,
      summary,
    };
  }
}
